services:
  - type: web
    name: client-analysis-backend
    runtime: python
    plan: free
    buildCommand: |
      pip install -r backend/requirements.txt
      python backend/model_utils.py
    startCommand: cd backend && gunicorn app:app --bind 0.0.0.0:$PORT --workers 2
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: CORS_ORIGINS
        value: https://your-netlify-app.netlify.app